import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Provider as JotaiProvider } from "jotai"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white h-screen w-screen overflow-hidden`}
      >
        <JotaiProvider>
          {children}
        </JotaiProvider>
      </body>
    </html>
  )
}
